#! /usr/bin/perl

use v5.10;
use strict;
use warnings;

use Getopt::Long qw<GetOptions :config gnu_getopt>;
use DateTime;

use FindBin '$Bin';
use lib "$Bin/lib";
use App::S3::MySQL::Backup;

my $USAGE = <<'EOF';
Usage: db_backup [OPTION]...

Back up databases, and clean up old backups.  Expects to be run hourly.

Options:

  --verbose Verbose mode
  --username USER
      Connect to the database as the given USER (required)
  --password PASSWORD
      Connect to the database with the given PASSWORD
  --directory BACKUP_DIR
      Store and delete backups in the given BACKUP_DIR (required)
  --Prefix PREFIX
      Fixed part of filename
  --Bucket Amazon S3 bucket to use

EOF

GetOptions(\my %OPT, qw<help|? version username=s password=s database|db=s
                        directory=s timestamp=s Prefix=s Bucket=s>)
    or die $USAGE;

if ($OPT{help}) {
    print $USAGE;
    exit 0;
}

for (qw<username directory>) {
    die "The -$_ option is required" if !exists $OPT{$_};
}

$OPT{Prefix} //= 'magnum_db.sql';

my $app = App::S3::MySQL::Backup->new(\%OPT);
$app->run;
